# Generated by Django 4.0.2 on 2022-02-10 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/Brands')),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/Category')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/Slideshow')),
            ],
            options={
                'db_table': 'Slideshow',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/SubCategory')),
            ],
            options={
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.BigIntegerField(default=0)),
                ('old_price', models.BigIntegerField(default=0)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/Products')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
