# Generated by Django 4.0.2 on 2023-04-01 05:06

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/editor')),
                ('blog_summary', django_mysql.models.SizedTextField(null=True, size_class=2)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default=' ')),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('date_time_picker', models.DateTimeField(default=datetime.datetime.now)),
                ('number_of_views', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/Brands')),
                ('discount', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BigIntegerField(default=0)),
                ('fullname', models.CharField(default='', max_length=20)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('review', models.CharField(default='', max_length=300)),
                ('categories', models.CharField(default='', max_length=200)),
                ('product_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'ProductReview',
            },
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/Products')),
                ('products_type', models.CharField(default='***', max_length=200)),
                ('product_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'ProductsImage',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('products_type', models.CharField(default='***', max_length=200)),
                ('product_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'ProductSpecification',
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='default', max_length=200)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/Slideshow')),
                ('upload', models.BooleanField(default=0, help_text='0:not_uploaded,1:uploaded')),
            ],
            options={
                'db_table': 'Slideshow',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/SubCategory')),
                ('categories', models.CharField(max_length=200)),
                ('discount', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_type', models.CharField(default='***', max_length=200)),
                ('product_id', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Wishlist',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='***', max_length=20)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/admin_user')),
                ('fullname', models.CharField(default='user', max_length=20)),
                ('location', models.CharField(default='***', max_length=50, null=True)),
                ('authorization', models.BooleanField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_type', models.CharField(default='***', max_length=200)),
                ('product_id', models.BigIntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 4, 1, 10, 51, 43, 444080))),
                ('verified', models.BooleanField(default=False)),
                ('delivering', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='LatestProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('coming_soon', models.BooleanField(default=0, help_text='0:none, 1:comingsoon')),
                ('featured_product', models.BooleanField(default=0, help_text='0:non-featured, 1:featured')),
                ('product_id', models.BigIntegerField(default=1)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 4, 1, 10, 51, 43, 439525))),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'LatestProducts',
            },
        ),
        migrations.CreateModel(
            name='LaptopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('coming_soon', models.BooleanField(default=0, help_text='0:none, 1:comingsoon')),
                ('featured_product', models.BooleanField(default=0, help_text='0:non-featured, 1:featured')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 4, 1, 10, 51, 43, 440187))),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'LaptopProducts',
            },
        ),
        migrations.CreateModel(
            name='EleAccProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('coming_soon', models.BooleanField(default=0, help_text='0:none, 1:comingsoon')),
                ('featured_product', models.BooleanField(default=0, help_text='0:non-featured, 1:featured')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'EleAccProducts',
            },
        ),
        migrations.CreateModel(
            name='DesktopsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('coming_soon', models.BooleanField(default=0, help_text='0:none, 1:comingsoon')),
                ('featured_product', models.BooleanField(default=0, help_text='0:non-featured, 1:featured')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 4, 1, 10, 51, 43, 440812))),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'DesktopsProducts',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('street_address', models.CharField(default='', max_length=50)),
                ('town_city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip', models.IntegerField(default='')),
                ('contact', models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='ComponentsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('coming_soon', models.BooleanField(default=0, help_text='0:none, 1:comingsoon')),
                ('featured_product', models.BooleanField(default=0, help_text='0:non-featured, 1:featured')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 4, 1, 10, 51, 43, 441993))),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'ComponentsProducts',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_type', models.CharField(default='***', max_length=200)),
                ('product_id', models.BigIntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('street_address', models.CharField(default='', max_length=50)),
                ('town_city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip', models.IntegerField(default='')),
                ('contact', models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Billing',
            },
        ),
        migrations.CreateModel(
            name='AppleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('coming_soon', models.BooleanField(default=0, help_text='0:none, 1:comingsoon')),
                ('featured_product', models.BooleanField(default=0, help_text='0:non-featured, 1:featured')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 4, 1, 10, 51, 43, 441420))),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'AppleProducts',
            },
        ),
    ]
