# Generated by Django 4.0.2 on 2022-02-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='discount',
            field=models.BigIntegerField(default=0),
        ),
    ]
