# Generated by Django 4.0.2 on 2022-02-10 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_brands_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='admin_panel.category'),
            preserve_default=False,
        ),
    ]
