# Generated by Django 4.0.2 on 2022-02-10 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0003_subcategory_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='***', max_length=20)),
                ('authorization', models.CharField(default=0, help_text='0:admin, 1:customer', max_length=10)),
                ('photo_img', models.ImageField(blank=True, default=0, null=True, upload_to='photos/admin_user')),
                ('fullname', models.CharField(default='user', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
