# Generated by Django 4.0.2 on 2022-02-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='discount',
            field=models.BigIntegerField(default=0),
        ),
    ]
