# Generated by Django 4.0.2 on 2022-02-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='upload',
            field=models.BooleanField(default=0, help_text='0:not_uploaded,1:uploaded'),
        ),
    ]
