# Generated by Django 4.0.2 on 2022-02-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_slideshow_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='latest_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.FloatField(default=0.0),
        ),
    ]
