# Generated by Django 4.0.2 on 2022-02-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_products_latest_price_alter_products_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_img',
            field=models.ImageField(blank=True, default='default', null=True, upload_to='photos/admin_user'),
        ),
    ]
