# Generated by Django 4.0.2 on 2022-02-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_profile_photo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='authorization',
        ),
    ]
