# Generated by Django 4.0.2 on 2022-02-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='street_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='zip',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='street_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='zip',
            field=models.IntegerField(default=''),
        ),
    ]
