# Generated by Django 4.0.2 on 2022-02-21 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_alter_billing_user_alter_delivery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='contact',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='contact',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
