# Generated by Django 4.0.2 on 2022-03-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_products_product_specification_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_specification_list',
        ),
        migrations.DeleteModel(
            name='ProductSpecificationList',
        ),
    ]
