# Generated by Django 4.0.2 on 2022-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_remove_products_product_specification_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='description',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
