# Generated by Django 4.0.2 on 2022-03-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_productspecification_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo_img',
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/Products')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductsImage', to='admin_panel.products')),
            ],
            options={
                'db_table': 'ProductsImage',
            },
        ),
    ]
