# Generated by Django 4.0.2 on 2022-03-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_remove_products_photo_img_productsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='products',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='productspecification', to='admin_panel.products'),
        ),
    ]
