# Generated by Django 4.0.2 on 2022-03-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_productspecification_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'AppleProducts',
            },
        ),
        migrations.CreateModel(
            name='ComponentsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'ComponentsProducts',
            },
        ),
        migrations.CreateModel(
            name='DesktopsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'DesktopsProducts',
            },
        ),
        migrations.CreateModel(
            name='EleAccProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'EleAccProducts',
            },
        ),
        migrations.CreateModel(
            name='LaptopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'LaptopProducts',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsimage',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='products',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='products_type',
            field=models.CharField(default='***', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='products_type',
            field=models.CharField(default='***', max_length=200),
        ),
        migrations.AddField(
            model_name='productsimage',
            name='product_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsimage',
            name='products_type',
            field=models.CharField(default='***', max_length=200),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='products_type',
            field=models.CharField(default='***', max_length=200),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products_type',
            field=models.CharField(default='***', max_length=200),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
