# Generated by Django 4.0.2 on 2022-03-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_appleproducts_componentsproducts_desktopsproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='categories',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
