# Generated by Django 4.0.2 on 2022-03-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_alter_subcategory_categories_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleproducts',
            name='coming_soon',
            field=models.BooleanField(default=0, help_text='0:none, 1:comingsoon'),
        ),
        migrations.AddField(
            model_name='componentsproducts',
            name='coming_soon',
            field=models.BooleanField(default=0, help_text='0:none, 1:comingsoon'),
        ),
        migrations.AddField(
            model_name='desktopsproducts',
            name='coming_soon',
            field=models.BooleanField(default=0, help_text='0:none, 1:comingsoon'),
        ),
        migrations.AddField(
            model_name='eleaccproducts',
            name='coming_soon',
            field=models.BooleanField(default=0, help_text='0:none, 1:comingsoon'),
        ),
        migrations.AddField(
            model_name='laptopproducts',
            name='coming_soon',
            field=models.BooleanField(default=0, help_text='0:none, 1:comingsoon'),
        ),
        migrations.AlterField(
            model_name='appleproducts',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='componentsproducts',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='desktopsproducts',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='eleaccproducts',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='laptopproducts',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
