# Generated by Django 4.0.2 on 2022-03-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_appleproducts_coming_soon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('stock', models.BigIntegerField(default=0)),
                ('latest_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(default=0.0)),
                ('coming_soon', models.BooleanField(default=0, help_text='0:none, 1:comingsoon')),
                ('product_id', models.BigIntegerField(default=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brands')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
            ],
            options={
                'db_table': 'LatestProducts',
            },
        ),
    ]
