# Generated by Django 4.0.2 on 2022-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_latestproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleproducts',
            name='featured_product',
            field=models.BooleanField(default=0, help_text='0:non-featured, 1:featured'),
        ),
        migrations.AddField(
            model_name='componentsproducts',
            name='featured_product',
            field=models.BooleanField(default=0, help_text='0:non-featured, 1:featured'),
        ),
        migrations.AddField(
            model_name='desktopsproducts',
            name='featured_product',
            field=models.BooleanField(default=0, help_text='0:non-featured, 1:featured'),
        ),
        migrations.AddField(
            model_name='eleaccproducts',
            name='featured_product',
            field=models.BooleanField(default=0, help_text='0:non-featured, 1:featured'),
        ),
        migrations.AddField(
            model_name='laptopproducts',
            name='featured_product',
            field=models.BooleanField(default=0, help_text='0:non-featured, 1:featured'),
        ),
    ]
