# Generated by Django 4.0.2 on 2022-03-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_appleproducts_featured_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestproducts',
            name='featured_product',
            field=models.BooleanField(default=0, help_text='0:non-featured, 1:featured'),
        ),
    ]
