# Generated by Django 4.0.2 on 2022-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_latestproducts_featured_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BigIntegerField(default=0)),
                ('fullname', models.CharField(default='', max_length=20)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('review', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'ProductReview',
            },
        ),
    ]
