# Generated by Django 4.0.2 on 2022-03-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='categories',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
