# Generated by Django 4.0.2 on 2022-03-30 06:22

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_productreview_categories_productreview_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/editor')),
                ('blog_summary', django_mysql.models.SizedTextField(null=True, size_class=2)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default=' ')),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('date_time_picker', models.DateTimeField(default=datetime.datetime.now)),
                ('number_of_views', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'Blogs',
            },
        ),
    ]
