# Generated by Django 4.0.2 on 2022-04-04 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 12, 4, 25, 612247)),
        ),
        migrations.AddField(
            model_name='componentsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 12, 4, 25, 612247)),
        ),
        migrations.AddField(
            model_name='desktopsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 12, 4, 25, 612247)),
        ),
        migrations.AddField(
            model_name='laptopproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 12, 4, 25, 612247)),
        ),
    ]
