# Generated by Django 4.0.2 on 2022-04-08 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0044_alter_appleproducts_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 10, 23, 5, 790390)),
        ),
        migrations.AlterField(
            model_name='componentsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 10, 23, 5, 791386)),
        ),
        migrations.AlterField(
            model_name='desktopsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 10, 23, 5, 789360)),
        ),
        migrations.AlterField(
            model_name='laptopproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 10, 23, 5, 788392)),
        ),
    ]
