# Generated by Django 4.0.2 on 2022-04-08 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0045_alter_appleproducts_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 27, 52, 243266)),
        ),
        migrations.AlterField(
            model_name='appleproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 27, 52, 246242)),
        ),
        migrations.AlterField(
            model_name='componentsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 27, 52, 247239)),
        ),
        migrations.AlterField(
            model_name='desktopsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 27, 52, 245244)),
        ),
        migrations.AlterField(
            model_name='laptopproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 27, 52, 244248)),
        ),
    ]
