# Generated by Django 4.0.2 on 2022-04-08 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_latestproducts_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 28, 18, 831185)),
        ),
        migrations.AlterField(
            model_name='componentsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 28, 18, 832181)),
        ),
        migrations.AlterField(
            model_name='desktopsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 28, 18, 830187)),
        ),
        migrations.AlterField(
            model_name='laptopproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 28, 18, 830187)),
        ),
        migrations.AlterField(
            model_name='latestproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 14, 28, 18, 829188)),
        ),
    ]
