# Generated by Django 4.0.2 on 2022-04-10 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0047_alter_appleproducts_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorization',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='appleproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 13, 45, 9, 177868)),
        ),
        migrations.AlterField(
            model_name='componentsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 13, 45, 9, 177868)),
        ),
        migrations.AlterField(
            model_name='desktopsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 13, 45, 9, 177868)),
        ),
        migrations.AlterField(
            model_name='laptopproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 13, 45, 9, 177868)),
        ),
        migrations.AlterField(
            model_name='latestproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 13, 45, 9, 177868)),
        ),
    ]
