# Generated by Django 4.0.2 on 2022-04-14 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0048_profile_authorization_alter_appleproducts_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_uploaded',
        ),
        migrations.AddField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 13, 57, 23, 646956)),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appleproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 13, 57, 23, 643446)),
        ),
        migrations.AlterField(
            model_name='componentsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 13, 57, 23, 644441)),
        ),
        migrations.AlterField(
            model_name='desktopsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 13, 57, 23, 642450)),
        ),
        migrations.AlterField(
            model_name='laptopproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 13, 57, 23, 642450)),
        ),
        migrations.AlterField(
            model_name='latestproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 13, 57, 23, 641450)),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
