# Generated by Django 4.0.2 on 2023-04-01 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/VendorBrands')),
                ('discount', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'VendorBrands',
            },
        ),
        migrations.CreateModel(
            name='VendorSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos/VendorSubCategory')),
                ('categories', models.CharField(max_length=200)),
                ('discount', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'VendorSubCategory',
            },
        ),
    ]
