# Generated by Django 4.0.2 on 2023-04-06 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 12, 44, 34, 257174)),
        ),
        migrations.AlterField(
            model_name='componentsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 12, 44, 34, 257856)),
        ),
        migrations.AlterField(
            model_name='desktopsproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 12, 44, 34, 256543)),
        ),
        migrations.AlterField(
            model_name='laptopproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 12, 44, 34, 255949)),
        ),
        migrations.AlterField(
            model_name='latestproducts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 12, 44, 34, 255317)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 12, 44, 34, 260046)),
        ),
    ]
