# Generated by Django 4.0.2 on 2023-04-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='order',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
        migrations.AddField(
            model_name='billing',
            name='batch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='batch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='batch',
            field=models.IntegerField(default=0),
        ),
    ]
