# Generated by Django 4.0.2 on 2023-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_billing_order_remove_delivery_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
