# Generated by Django 4.0.2 on 2023-04-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_productreview_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='order',
        ),
    ]
